### ISSUE TITLE
Pal shows incomplete

### ISSUE THREAD

**Issue by Zodix** [EternalWraith/PalEdit#112]
Palworld Server v0.1.4.1
PalEdit v0.6.1
Pal shows incomplete，error log:
Warning: Player d720e381-0000-0000-0000-000000000000 Have character 55 not in containers, loaded: 5 / standby: 56
Error: Guild instance 4b6a5db4-4569-4de9-7669-9ab1400aa922 invalid, local items: 62, replace with 999 -> 999
Reload cache
{'Player1': '1fd08cdb-0000-0000-0000-000000000000', 'Player2': '626d9b7e-0000-0000-0000-000000000000', 'Player3': '3bcd8a03-0000-0000-0000-000000000000', 'Player4': '22daa721-0000-0000-0000-000000000000', 'Player5': 'd720e381-0000-0000-0000-000000000000'}
Created Entity of type HawkBird: <PalInfo.PalObject object at 0x00000254B3D43B50> - Lucky: True Boss: False
Error occured: 'EPalWazaID::None'
Traceback (most recent call last):
  File "PalEdit.py", line 596, in loadpal
  File "PalInfo.py", line 222, in __init__
  File "PalInfo.py", line 246, in CleanseAttacks
KeyError: 'EPalWazaID::None'
Found Player Character
Created Entity of type ColorfulBird: <PalInfo.PalObject object at 0x00000254B3D43BD0> - Lucky: False Boss: False
Error occured: 'EPalWazaID::None'
Traceback (most recent call last):
  File "PalEdit.py", line 596, in loadpal
  File "PalInfo.py", line 222, in __init__
  File "PalInfo.py", line 246, in CleanseAttacks

**Comment by EternalWraith** [comment]
Is this fixed in the newer versions?
