### ISSUE TITLE
Error when loading save

### ISSUE THREAD

**Issue by thesimpleway1** [EternalWraith/PalEdit#12]
After extracting the json, trying to load the save gives me the following error:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\dhohg\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\dhohg\Palworld\Paledit\PalEdit-main\PalEdit.py", line 121, in loadfile
    paldata = data['properties']['worldSaveData']['value']['CharacterSaveParameterMap']['value']
KeyError: 'properties'`

**Comment by EternalWraith** [comment]
Make sure you are using the newest version of SaveTools :)

**Comment by thesimpleway1** [comment]
> Make sure you are using the newest version of SaveTools :)

Worked.

Sorry for that.
