### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Zrudkin90** [EternalWraith/PalEdit#23]
Opening file C:/Users/DomJ/OneDrive/Desktop/PalEdit/palworld-save-tools-main/Level.sav.json
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\DomJ\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DomJ\OneDrive\Desktop\PalEdit\palworld-save-tools-main\PalEdit.py", line 123, in loadfile
    paldata = data['root']['properties']['worldSaveData']['Struct']['value']['Struct']['CharacterSaveParameterMap']['Map']['value']
              ~~~~^^^^^^^^
KeyError: 'root'

Any idea what i do here?
also this Level.sav.json is from a dedicated server that 5 people play on.

**Comment by Zrudkin90** [comment]
figured it out!

**Comment by Zrudkin90** [comment]
Thanks
