### ISSUE TITLE
zlib.error: Error -3 while decompressing data: invalid block type

### ISSUE THREAD

**Issue by geocine** [EternalWraith/PalEdit#38]
Log:
```
Opening file C:/Users/geocine/Downloads/PalEdit.v0.4.6/Level.sav
Converting C:/Users/geocine/Downloads/PalEdit.v0.4.6/Level.sav to JSON, saving to C:/Users/geocine/Downloads/PalEdit.v0.4.6/Level.sav.json
Decompressing sav file
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\ACM\SW\PalEdit\PalEdit.py", line 430, in converttojson
    doconvertjson(file)
  File "C:\ACM\SW\PalEdit\PalEdit.py", line 433, in doconvertjson
    SaveConverter.convert_sav_to_json(file, file.replace(".sav", ".sav.json"), compress)
  File "C:\ACM\SW\PalEdit\SaveConverter.py", line 76, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ACM\SW\PalEdit\lib\palsav.py", line 25, in decompress_sav_to_gvas
    uncompressed_data = zlib.decompress(data[12:])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: invalid block type
```

Environment:
```
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
PalEdit v0.4.6
```
Save:
https://file.io/CDoraKiguWAz

**Comment by EternalWraith** [comment]
Not a PalEdit error, this is a SaveTools error

**Comment by geocine** [comment]
But you bundled the save tools editor so that means you have to update it
